### ISSUE TITLE
obsdim

### ISSUE THREAD

**Issue by willtebbutt** [JuliaGaussianProcesses/KernelFunctions.jl#43] opened 2020-03-11 17:30 UTC
This relates to #9 and presumably #10 .

The `obsdim` keyword is a bit annoying as it has to be propagated around the entire codebase.

Arguably a better solution for vector-valued inputs is to introduce  `ColVecs <: AbstractVector` and `RowVecs <: AbstractVector` types, as done in Stheno, so that it's clear how things are being treated, and functions like `kernelmatrix` that, in the context of non-`BaseKernel`s don't need to know about this information, don't have to worry about it.

@theogf @devmotion any thoughts?

edit: this obviously generalises to any input type that you fancy from an API perspective.

**Comment by theogf** [comment] 2020-03-11 18:03
I tend to like `obsdim` because it is also used in `Distances.jl` and `MLDataUtils.jl` for example. To be honest when I see `RowVecs` or `ColVecs` I intuitively have no idea what is what...

**Comment by willtebbutt** [comment] 2020-03-11 18:24
That's fair I guess.

When you see a `RowVecs`, you should intuitively think "this is an efficiently-represented vector of row-vectors" and with `ColVecs` "this is an efficiently-represented vector of column-vectors". Is there something unclear about that? I would genuinely like to know if I'm the only one who think this is a really helpful way to think about this stuff...

**Comment by devmotion** [comment] 2020-03-12 10:38
I'm not a fan of carrying around `obsdim` everywhere. It tries to solve a problem that only exists since observations in matrixform can be viewed differently, so the main problem is not a conceptual/mathematical one (and does not even exist for other input spaces, e.g., when dealing with distributions) but only caused by how we store the inputs.

I'm wondering if one actually has to support both column- and row-vectors (e.g., it is really necessary to provide explicit support for row vectors in Distances, couldn't the user just provide the lazy transpose of the matrix of observations in this case?). Would it make sense to only use column vectors if one is mainly/only interested in operations based on full observations and not individual components of observations?

I had a look at `ColVecs` in Stheno, and I think in principle it is a neat idea to avoid this issue. Recently, I had to deal with similar questions in CalibrationErrors, since I wanted to add support for arbitrary distributions and hence it felt more naturally to view the predictions as vectors of vectors (in case of categorical distributions) and general distributions otherwise. Currently, internally I'm working with vectors of vectors to which user-provided matrices are converted in the user-facing function (without `obsdim` specification since Distributions uses column vectors). The problem that I see with using `ColVecs` and `RowVecs` in this situation is that it will be highly inefficient and create a lot of allocations: I iterate over all combinations of samples by just retrieving `observations[i]` and `observations[j]`, and with a proper vector of vectors this does not create any allocations - however, with `ColVecs` (and probably a future `RowVecs` implementation) every indexing operation allocates a new vector (https://github.com/willtebbutt/Stheno.jl/blob/cd4ec480a04e287345df826bfcc116ff5732168f/src/util/abstract_data_set.jl#L27).

**Comment by willtebbutt** [comment] 2020-03-12 14:18
Yeah -- it only makes sense to use `ColVecs` if it makes sense with your access patterns. For example, in your case it probably _does_ make sense to quite literally use a vector-of-vectors.

I agree that one of the issues with `obsdim` is, for example, that it's really not necessary if your inputs are `Real`s, and you therefore want to represent a dataset as a `Vector{<:Real}`. Similarly, if you have @devmotion 's case and you actually do want to store your data as a `Vector{<:Vector{<:Real}}`, it's quite clear how you mean for things to work.

However, clearly it is necessary to somehow specify how to treat the dimensions of a matrix of data. So you can either do this by

1. modifying the API for everything that operates on all of the data types -- currently done with `obsdim`.
2. modifying the data types a bit so that it's unambiguous how they are to be treated by your algorithms -- unambiguous for dataset `Vector{<:Real}` or `Vector{<:Vector{<:Real}}` so no modification necessary, but ambiguous for `Matrix{<:Real}` so wrapper type needed to disambiguate somehow
3. have a mish-mash of the two, depending on the data type

I think the third option is probably a terrible idea. I prefer the second option to the first because I personally find it very straightforward to comprehend and it makes implementing stuff incredibly clean -- you always know that a dataset is represented by something that subtypes `AbstractVector`, and you can therefore query things like its `length`. The only time that you have to figure out how to actually do stuff is when computing eg. pairwise distances between the elements of the data set, which seems to me like the right time to have to worry about that kind of thing.

(If there's a fourth approach, I'm unaware of it)

**Comment by willtebbutt** [comment] 2020-03-15 20:12
One other thing: some kernels are only defined for real-valued inputs eg. the Weiner or integrated-Weiner kernels, so it would be nice to be able to handle this at a dispatch level as opposed to just having to check whether or not the input matrix is `N x 1` or `1 x N`.

**Comment by willtebbutt** [comment] 2020-04-21 23:03
As discussed in #83 we don't seem to have reached a consensus on this, so I'm going to try harder to explain my position.

## Meaning of `ColVecs`

It just packages the data and the information about how to interpret the data into a single object. Specifically, if `X isa AbstractMatrix`, then `x = ColVecs(X)` means that `x` should be treated as a vector of vectors, where it happens to be the case that each vector is stored contiguously in memory in an object known as a `Matrix`, and its layout is such that each column of `X` is treated as a single data point. Thus `ColVecs(X)` is equivalent to `X, obsdim=2` as currently implemented.

For, concreteness et `X` be a `P x Q` `Matrix{Float64}`. Then

- `ColVecs(X)` === "the column vectors of `X`" === "`X` should be understood as a collection of `Q` column vectors, each of which has length `P`".
- `RowVecs(X)` === "the row vectors of `X`" === "`X` should be understood as a collection of `P` row vectors, each of which has length `Q`"

## ColVecs is as efficient as matrices

Using `ColVecs` does not sacrifice performance relative to using a matrix, because `ColVecs` does use a matrix under the hood and we use dispatch to specialise on that fact. To see this, look at the way that it is used in Stheno.jl. Specifically, consider the [EQ](https://github.com/willtebbutt/Stheno.jl/blob/a9a41981b8d25ae5188bb3873369daa26ac6f2b2/src/gp/kernel.jl#L94) implementation of `kernelmatrix` (called `pairwise` in Stheno.jl), copied + made more verbose below:

```julia
function pairwise(::EQ, x::AbstractVector, x′::AbstractVector)
    return exp.(.-pairwise(SqEuclidean(), x, x′) ./ 2)
end
```
It's implemented in terms of `AbstractVector`s `x` and `x′`. These are passed immediately to `pairwise` from `Distances.jl`. Note that the implementation is completely agnostic to the way in which the data are stored under the hood, provided that they're at least masquerading as a vector.

Making `ColVecs` play nicely with `Distances.jl` was straightforward. See [here](https://github.com/willtebbutt/Stheno.jl/blob/a9a41981b8d25ae5188bb3873369daa26ac6f2b2/src/util/distances.jl#L15). Unfortunately this code is more complicated than it needs to be (since writing this I've realised that it can be simplified significantly, but haven't got around to it yet), but it's just the following definition of `pairwise` for `ColVecs`:
```julia
pairwise(d::PreMetric, x::ColVecs, y::ColVecs) = pairwise(d, x.X, y.X; dims=2)
```
This makes it clear that all that the `ColVecs` type has done is bundle the `obsdim` information in with the data type, as opposed to requiring it to be propagated around separately. This lets us use dispatch to pull out the information about the way in which the data is stored only when it is relevant.

Had `Stheno.jl` already implemented a `RowVecs` data type, the definition would be
```julia
pairwise(d::PreMetric, x::RowVecs, y::RowVecs) = pairwise(d, x.X, y.X; dims=1)
```
ie. the `obsdim` parameter is the other way around.

The first takeaway is that you never need to call `getindex` on a `ColVecs` / `RowVecs` object when computing the kernel matrix. Indeed, pretty much the only in which you should call `getindex` is when printing to the REPL / other situations in which performance isn't a concern.

The second, and the one that makes the code cleaner, is that because the information about how the data is stored in memory is hidden inside the data type, we can pull it out only when its relevant to the computation being performed. To my mind is it clear that the only point at which this information is relevant in the above example is when we're computing the pairwise squared euclidean distance between each pair of points in our data set. At that point, you need to know how the data is represented in order to perform the computation most efficiently / correctly. Conversely, the implementation of `pairwise(::EQ, ::AbstractVector, ::AbstractVector)` doesn't need to know this information, and indeed it never appears in the function.


## `AbstractVector`s are cleaner than `AbstractMatrix`s

### How we currently represent data

- Data sets: abstract matrix.
- Data point: either vector or scalar

This has the particular issue that we have to pass the `obsdim` parameter around everywhere. This is particularly problematic in situations such as with `KernelSum`'s implementations of `kernelmatrix` etc. `KernelSum` doesn't ever need to know anything about how a data set is laid out in memory, it just needs to propagate the data on to the kernels that it sums over, so the fact that it has to explicitly handle information about the memory layout of the data is suboptimal.

Moreover, if your element type is a `Float64` and a dataset is therefore naturally represented as a `Vector{Float64}`, `KernelFunctions` must first transform it into an `N x 1` matrix. Similarly if you had, say, a dataset comprising `String`s, and hence a `Vector{String}`, you would have to reshape it into an `N x 1` `Matrix{String}`.

### How we could represent data

- Data set: abstract vector
- Data point: anything you like

This has the advantage that the `obsdim` parameter doesn't need to be passed around, thus not appearing in code where it's not used. It has been hidden in the data types, specifically `ColVecs` and `RowVecs`. Moreover, it only reappears when it's relevant eg. when you call out to a function from `Distances` and it need to know how data is laid out in memory.

## What the user sees

Current:
```julia
kernelfunction(k, X; obsdim=2)
```
Proposed:
```julia
kernelfunction(k, ColVecs(X))
```
This highlights that from a user perspective, the only difference that you'll ever see is a different way to specify the `obsdim`. And, of course, if your data is already a `Vector{Float64}` or something you don' even need to wrap it.


## nb

Knowing that `Stheno` requires data sets to be `AbstractVector`s makes its semantics much clearer. `pairwise(k, x, y)` takes on a clear and precise meaning when it's inputs are vectors -- compute the value of the kernel `k` for each pair of elements in `x` and `y`. It doesn't say anything about _how_ this computation should be performed of course, so you're free to make calls out to `Distances` etc, but it does specifically clearly _what_ should be computed. Moreover, the name `pairwise` makes sense in light of this.

**Comment by devmotion** [comment] 2020-04-22 06:09
I agree, that sounds a lot cleaner.

As a side remark, I think https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/issues/87 would be helpful for implementing the proposed representation of the data

>    Data set: abstract vector
>    Data point: anything you like

cleanly since regardless of how weird the input types are that we receive (and even if they are vectors) `kernelfunction(x, y)` would view `x` and `y` always as data points whereas `kernelmatrix` etc. would only operate on abstract vectors, i.e., data sets.

**Comment by theogf** [comment] 2020-04-22 08:51
Wow thanks for the detailed description of your proposal! At some point you could make a PR to add this to the docs!
I agree with everything except maybe for : 

> Current:
    kernelfunction(k, X; obsdim=2)
Proposed:
    kernelfunction(k, ColVecs(X))

I think both options should be available with `kernelfunction(k, X; obsdim = 2)` being a wrapper of `kernelfunction(k, ColVecs(X))`

**Comment by willtebbutt** [comment] 2020-04-22 09:09
> I think both options should be available with kernelfunction(k, X; obsdim = 2) being a wrapper of kernelfunction(k, ColVecs(X))

Good idea!

**Comment by willtebbutt** [comment] 2020-04-22 10:32
Great, will make a PR once #87 is resolved.

**Comment by devmotion** [comment] 2020-04-27 10:31
Fixed by https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/pull/99.

**Closed by devmotion** 2020-04-27 10:31 UTC
