### ISSUE TITLE
Trouble creating a custom kernel

### ISSUE THREAD

**Issue by YanniPapandreou** [JuliaGaussianProcesses/KernelFunctions.jl#204] opened 2020-12-08 13:57 UTC
Hi, I am finding KernelFunctions.jl very helpful for my work, so I'd like to say thanks for creating this first!

I am trying to create my own custom kernel. I open the REPL and try the following code based on what the documentation says on creating custom kernels:

```julia
using KernelFunctions
using HypergeometricFunctions

f(x) = pFq([0.5],[0.5*2],x)

struct MyKernel <: Kernel end

KernelFunctions.kappa(::MyKernel, d2::Real) = f(-0.5*d2)
KernelFunctions.metric(::MyKernel) = SqEuclidean()
```

I then try calling the following:
```julia
KernelFunctions.kappa(MyKernel(),3) ## this works
KernelFunctions.kappa(MyKernel(),3,1) ## this doesn't work
```

Am I forgetting to do something to get this to work?

**Comment by theogf** [comment] 2020-12-08 14:19
Hi @YanniPapandreou, the `kappa` function is actually the call made on the computed distances between two vectors, which you correctly defined here.
If you want to compute the kernel function between two elements given your created `MyKernel` you can now do `MyKernel()(3, 1)`.
However note that `kappa` is only used by `SimpleKernel`, which has stronger restrictions (that your kernel seem to satisfy). The only correction you need to do is to define your kernels as `struct MyKernel <: KernelFunctions.SimpleKernel end`

**Comment by willtebbutt** [comment] 2020-12-08 17:35
@theogf just taken a look at our docs -- they appear to be out of date, and are presumably the cause of this confusion. We should probably update them to reflect the current state of the package.

**Comment by devmotion** [comment] 2020-12-08 17:41
To me it seems the documentation is up to date, both the [stable branch](https://juliagaussianprocesses.github.io/KernelFunctions.jl/stable/create_kernel/) and the [development version](https://juliagaussianprocesses.github.io/KernelFunctions.jl/dev/create_kernel/). I assume the problem is that some old version is available at https://juliagaussianprocesses.github.io/KernelFunctions.jl/create_kernel/ and linked from the README. I don't know why that's the case.

**Comment by willtebbutt** [comment] 2020-12-08 17:43
Ah, yes, that's indeed the one I followed. Definitely makes for an easier fix 😂

**Comment by devmotion** [comment] 2020-12-08 17:43
What's even worse, we also link to this strange version in the description of the repo.

**Comment by devmotion** [comment] 2020-12-08 17:46
I assume that at some points Documenter was not set up properly and therefore the subfolders `create_kernel` etc. were created in https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/tree/gh-pages and still exist, even though the configuration seems to be correct now.

**Comment by theogf** [comment] 2020-12-08 17:47
I just updated the link in the description, if that's okay I will just directly commit on the README

**Comment by devmotion** [comment] 2020-12-08 17:47
I think the `gh-pages` branch has to be cleaned and fixed as well.

**Comment by devmotion** [comment] 2020-12-08 17:51
Just to be clear: the current configuration of Documenter seems to be fine, the version tagging, stable, and dev structure seems to work now. It is just the unversioned remainder of the previous, apparently incorrect setup that have to be removed.

**Comment by YanniPapandreou** [comment] 2020-12-08 19:36
@theogf Thanks a lot that fixed it for me! @willtebbutt thanks, I was following the documentation which was a bit different then the solution, though I'm relatively new to Julia so there might be some aspects I just haven't understood!

**Comment by willtebbutt** [comment] 2020-12-08 19:39
> @theogf Thanks a lot that fixed it for me! @willtebbutt thanks, I was following the documentation which was a bit different then the solution, though I'm relatively new to Julia so there might be some aspects I just haven't understood!

No, I think you followed the old docs well, we just had an old docs link. It's now been updated, so if you go back to it from the link in the README, you should find the most recent docs. Let us know if you have any more problems, very happy to help :)

**Comment by YanniPapandreou** [comment] 2020-12-08 20:37
@willtebbutt Thanks a lot, I have seen the updated docs :)

**Comment by theogf** [comment] 2020-12-09 10:00
I am closing the issue now :)

**Closed by theogf** 2020-12-09 10:00 UTC
